services:
  postgres:
    image: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
      target: db
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
       - postgres_volume:/var/lib/home_serice_db/data
    networks:
      - backend

  home_service:
    image: ivanmakaryshchev/home_service
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    ports:
      - "${PORT}:${PORT}"
    environment: 
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    restart: on-failure
    volumes:
            - ./src:/app/src
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_volume:

networks:
  backend:
    name: backend_network
    driver: bridge
