services:
  postgres:
    image: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
      target: db
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
       - home_service_db_volume:/var/lib/home_serice_db/data
    networks:
      - docker_postgres

  home_service:
    image: ivanmakaryshchev/home_service
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    ports:
      - "${PORT}:${PORT}"
    environment: 
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    volumes:
            - ./:/app/
            - home_service_db_volume:/app/node_modules
    depends_on:
      - postgres
    networks:
      - docker_postgres

volumes:
  home_service_db_volume:

networks:
  docker_postgres:
    name: postgress_network
    driver: bridge
